### ISSUE TITLE
curl breaks after github org name change of tfsec

### ISSUE THREAD

**Issue by yashmurty** [reviewdog/action-tfsec#22]
curl breaks after github org name change of tfsec.

```
##[group*** Installing tfsec (latest) ... https://github.com/tfsec/tfsec
curl: (22) The requested URL returned error: 404 
```
Old: https://github.com/tfsec/tfsec
New: https://github.com/aquasecurity/tfsec

The relevant code:
https://github.com/reviewdog/action-tfsec/blob/master/script.sh#L39
```
echo "::group:: Installing tfsec (${INPUT_TFSEC_VERSION}) ... https://github.com/tfsec/tfsec"
  test ! -d "${TFSEC_PATH}" && install -d "${TFSEC_PATH}"

  if [[ "${INPUT_TFSEC_VERSION}" = "latest" ]]; then
    tfsec_version=$(curl --silent https://api.github.com/repos/tfsec/tfsec/releases/latest | jq -r .tag_name)
```

**Comment by Vlaaaaaaad** [comment]
🤦 wasn't GitHub supposed to support redirects for repo moves? 

Waiting for the checks to pass on the PR and I'll merge and release!

**Comment by Vlaaaaaaad** [comment]
[v1.10.0](https://github.com/reviewdog/action-tfsec/releases/tag/v1.10.0) was released with the PR fixing this 🎉
