### ISSUE TITLE
Deprecation warning for `set-output`, new release needed

### ISSUE THREAD

**Issue by markus-dobel-fioneer** [reviewdog/action-tfsec#48]
Github Actions emits this warning for every run of this action (latest release version, 1.15.2)

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-sav
```

I see that the necessary change is already in the main branch, most probably it just needs to be tagged/released.

**Comment by shogo82148** [comment]
[v1.15.3](https://github.com/reviewdog/action-tfsec/releases/tag/v1.15.3) has been released.
