### ISSUE TITLE
Action fails to download tfsec

### ISSUE THREAD

**Issue by paul-pop** [reviewdog/action-tfsec#8]
Hi there 👋 

I noticed there were a few [tfsec releases](https://github.com/tfsec/tfsec/releases) in the last 24 hours which broke this action as some extra binaries were introduced.

The result of:

```bash
wget -q https://api.github.com/repos/liamg/tfsec/releases/latest -O - | grep -o -E "https://.+?-linux-amd64"
```

now yields:

```bash
https://github.com/tfsec/tfsec/releases/download/v0.32.1/tfsec-checkgen-linux-amd64
https://github.com/tfsec/tfsec/releases/download/v0.32.1/tfsec-linux-amd64
```

So it fails to download into a tfsec binary. I'll raise a PR request shortly for the fix.

**Comment by Vlaaaaaaad** [comment]
Thank you so much for reporting and fixing this @paul-pop!
